nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.0.cjs

npmRegistries:
    'https://npm.pkg.github.com':
        npmAlwaysAuth: true
        npmAuthToken: ${{ secrets.GITHUB_TOKEN }}

npmScopes:
    field-share:
        npmPublishRegistry: 'https://npm.pkg.github.com'
        npmRegistryServer: 'https://npm.pkg.github.com'
